---
- name: Running playbooks
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd
    yum:
     name: httpd
     state: present
  - name: Starting web server
    service:
     name: httpd
     state: started
     enabled: true
  - name: copy conf file
    copy:
      src: /home/ec2-user/index/
      dest: /var/www/html/
  - name: "server restart"
    service:
      name: "httpd"
      state: restarted