---
- name: Running playbooks
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd
    yum:
     name: httpd
     state: present
  - name: Starting web server
    service:
     name: httpd
     state: started
     enabled: true